# vim: ft=yaml.docker-compose
---
name: ns

include:
  - ext/docker-compose-snippets/tailscale.yaml

services:
  coredns:
    image: ghcr.io/damomurf/coredns-tailscale:latest
    environment:
      NAME: ${COMPOSE_PROJECT_NAME}
      COREDNS_AUTHKEY: ${COREDNS_AUTHKEY}
    configs:
      - Corefile
    volumes:
      - coredns_state:/root
    restart: unless-stopped
    extends:
      file: ext/docker-compose-snippets/tailscale-app-base.yaml
      service: tailscale-app-base

configs:
  Corefile:
    file: ./Corefile

volumes:
  coredns_state:
