# vim: ft=yaml.docker-compose
name: ns${ID}

include:
  - ext/docker-compose-snippets/tailscale.yaml

services:
  coredns:
    image: ghcr.io/damomurf/coredns-tailscale:latest
    environment:
      - ID=${ID}
    configs:
      - Corefile
    volumes:
      - coredns_state:/root
    secrets:
      - coredns_authkey
    restart: unless-stopped
    extends:
      file: ext/docker-compose-snippets/tailscale-app-base.yaml
      service: tailscale-app-base

configs:
  Corefile:
    file: ./Corefile

secrets:
  ts_authkey:
    file: ./ts_authkey.txt
  coredns_authkey:
    file: ./coredns_authkey.txt

volumes:
  coredns_state:
